export let screenData = [
    {
        consultingroomName: "普通外科二病区门诊",
        staffName: "刘胜息",
        appointVisitno: "复诊020",
        patientName: "宿谭",
        waitingList: [
            ["001-那*波", "复诊0202-沈*辰", "0034-张*晨", "预约003-谭*飞", "过号003-刘*强", "0051-张*"],
            ["0089-牛*", "预约005-沈*辰", "0089-张*", "预约090-谭*", "0101-刘*", "0090-张*"],
        ],
        overList: [
            ["过号001-那*波", "过号002-深*成"],
            ["过号003-刘*", "过号004-张*博"],
            ["过号005-刘*", "过号006-牛*牛"],
        ],
    },
    {
        consultingroomName: "男性生殖医学科(北)二室",
        staffName: "李佳薇",
        appointVisitno: "预约21",
        patientName: "陶佳佳",
        waitingQueue: [
            { appointVisitno: "复诊003", patientName: "牛牛" },
            { appointVisitno: "001", patientName: "马飞飞" },
            { appointVisitno: "006", patientName: "及牛波" },
            { appointVisitno: "007", patientName: "路儿哇大" },
        ],
    },
    {
        consultingroomName: "心血管内科专家门诊一室",
        staffName: "蒋铎",
        appointVisitno: "预约333",
        patientName: "陈晓鹏",
        waitingQueue: [
            { appointVisitno: "001", patientName: "那第波" },
            { appointVisitno: "复诊0202", patientName: "沈梦辰" },
            { appointVisitno: "0034", patientName: "张碧晨" },
            { appointVisitno: "预约003", patientName: "谭龙飞" },
            { appointVisitno: "过号003", patientName: "刘比强" },
            { appointVisitno: "0051", patientName: "张三" },
            { appointVisitno: "010", patientName: "牛得很" },
            { appointVisitno: "预约3", patientName: "张刘思" },
        ],
    },
    {
        consultingroomName: "普通外科二病区门诊",
        staffName: "高留搭第",
        appointVisitno: "复诊0200",
        patientName: "王建华",
        waitingQueue: [
            { appointVisitno: "预约003", patientName: "谭龙飞" },
            { appointVisitno: "过号003", patientName: "刘比强" },
        ],
    },
    {
        consultingroomName: "普通外科二病区门诊",
        staffName: "赵云",
        appointVisitno: "036",
        patientName: "迪丽热巴",
        waitingQueue: [
            { appointVisitno: "001", patientName: "那第波" },
            { appointVisitno: "复诊0202", patientName: "沈梦辰" },
            { appointVisitno: "0034", patientName: "张碧晨" },
            { appointVisitno: "预约003", patientName: "谭龙飞" },
            { appointVisitno: "过号003", patientName: "刘比强" },
            { appointVisitno: "0051", patientName: "张三" },
            { appointVisitno: "010", patientName: "牛得很" },
            { appointVisitno: "预约3", patientName: "张刘思" },
            { appointVisitno: "过号003", patientName: "刘比强" },
            { appointVisitno: "0051", patientName: "张三" },
            { appointVisitno: "010", patientName: "牛得很" },
            { appointVisitno: "预约3", patientName: "张刘思" },
            { appointVisitno: "过号003", patientName: "刘比强" },
            { appointVisitno: "0051", patientName: "张三" },
            { appointVisitno: "010", patientName: "牛得很" },
            { appointVisitno: "预约3", patientName: "张刘思" },
        ],
    },

    {
        consultingroomName: "测试诊室",
        staffName: "赵云",
        appointVisitno: "036",
        patientName: "迪丽热巴",
        waitingQueue: [
            { appointVisitno: "001", patientName: "那第波" },
            { appointVisitno: "复诊0202", patientName: "沈梦辰" },
            { appointVisitno: "0034", patientName: "张碧晨" },
            { appointVisitno: "预约003", patientName: "谭龙飞" },
            { appointVisitno: "过号003", patientName: "刘比强" },
            { appointVisitno: "0051", patientName: "张三" },
            { appointVisitno: "010", patientName: "牛得很" },
            { appointVisitno: "预约3", patientName: "张刘思" },
            { appointVisitno: "过号003", patientName: "刘比强" },
            { appointVisitno: "0051", patientName: "张三" },
            { appointVisitno: "010", patientName: "牛得很" },
            { appointVisitno: "预约3", patientName: "张刘思" },
            { appointVisitno: "过号003", patientName: "刘比强" },
            { appointVisitno: "0051", patientName: "张三" },
            { appointVisitno: "010", patientName: "牛得很" },
            { appointVisitno: "预约3", patientName: "张刘思" },
        ],
    },
];

let tempData = [
    [
        { appointVisitno: "001", patientName: "李*" },
        { appointVisitno: "复诊0020", patientName: "孙*对" },
        { appointVisitno: "过号0021", patientName: "牛*糊" },
        // { appointVisitno: "00310", patientName: "张建飞" },
    ],
    [
        { appointVisitno: "001", patientName: "李*" },
        { appointVisitno: "复诊0020", patientName: "孙*对" },
    ],
    [{ appointVisitno: "002", patientName: "李春芳" }]]